### ISSUE TITLE
V1 API

### ISSUE THREAD

**Issue by quimarche** [rngtng/NabaztagHackKit#1]
Hi Tobias

Very glad to see a reference to Trudy ;-) I've been encouraged by your work to look at creating a V1 version but can't find any documentation anywhere. Do you know where I might find some?

Cheers

Chris

**Comment by rngtng** [comment]
Hey chris, nice to hear you plan to push V1 :-) What kind of docu are you looking for? Here are commands and some examples on the MTL code:

https://github.com/rngtng/NabaztagHackKit/tree/master/ext/bytecode  (They look way better in your texteditor, as github doesn't render Markdown tables)

does this help?
